# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

require 'faker'

include Faker

formats_brands= %w{Honda Hyundai Bucati BMW Ford Fiat Audi LandRover Mitsubushi Ferrari RollsRoyce Suzuki volkswagen Bajaj Mazda Mercedes-Benz Mercury Merkur MG Mini Nissan Oldsmobile Opel Peugeot Plymouth Pontiac Porsche Ram Renault Rolls Royce Rover Saab Saturn Scion Smart Sterling Subaru Suzuki Toyota Triumph Volkswagen Volvo Yugo }

formats_cars = %w{ CORVETTE STING RAY AD UNIVERSAL CAMARO DA MASTER MANGUSTA PANTERA DEAUVILLE LONGCHAMP BLAZER EC STANDARD MONTE CARLO EA MASTERFC STANDARDFA MASTER IMPALA MASTER GAGBHAHB CAPRICE MASTER JAJB MONZA TYPHOON TEMPEST THUNDERBOLT TALISMAN CORVETTE STING RAY AD UNIVERSAL CAMARO DA MASTER MANGUSTA PANTERA DEAUVILLE LONGCHAMP BLAZER EC STANDARD MONTE CARLO EA MASTERFC STANDARDFA MASTER IMPALA MASTER GAGBHAHB CAPRICE MASTER JAJB MONZA TYPHOON TEMPEST THUNDERBOLT TALISMAN CORVETTE STING RAY AD UNIVERSAL CAMARO DA MASTER MANGUSTA PANTERA DEAUVILLE LONGCHAMP BLAZER EC STANDARD MONTE CARLO EA MASTERFC STANDARDFA MASTER IMPALA MASTER GAGBHAHB CAPRICE MASTER JAJB MONZA TYPHOON TEMPEST THUNDERBOLT TALISMAN CORVETTE STING RAY AD UNIVERSAL CAMARO DA MASTER MANGUSTA PANTERA DEAUVILLE LONGCHAMP BLAZER EC STANDARD MONTE CARLO EA MASTERFC STANDARDFA MASTER IMPALA MASTER GAGBHAHB CAPRICE MASTER JAJB MONZA TYPHOON TEMPEST THUNDERBOLT TALISMAN CORVETTE STING RAY AD UNIVERSAL CAMARO DA MASTER MANGUSTA PANTERA DEAUVILLE LONGCHAMP BLAZER EC STANDARD MONTE CARLO EA MASTERFC STANDARDFA MASTER IMPALA MASTER GAGBHAHB CAPRICE MASTER JAJB MONZA TYPHOON TEMPEST THUNDERBOLT TALISMAN CORVETTE STING RAY AD UNIVERSAL CAMARO DA MASTER MANGUSTA PANTERA DEAUVILLE LONGCHAMP BLAZER EC STANDARD MONTE CARLO EA MASTERFC STANDARDFA MASTER IMPALA MASTER GAGBHAHB CAPRICE MASTER JAJB MONZA TYPHOON TEMPEST THUNDERBOLT TALISMAN CORVETTE STING RAY AD UNIVERSAL CAMARO DA MASTER MANGUSTA PANTERA DEAUVILLE LONGCHAMP BLAZER EC STANDARD MONTE CARLO EA MASTERFC STANDARDFA MASTER IMPALA MASTER GAGBHAHB CAPRICE MASTER JAJB MONZA TYPHOON TEMPEST THUNDERBOLT TALISMAN CORVETTE STING RAY AD UNIVERSAL CAMARO DA MASTER MANGUSTA PANTERA DEAUVILLE LONGCHAMP BLAZER EC STANDARD MONTE CARLO EA MASTERFC STANDARDFA MASTER IMPALA MASTER GAGBHAHB CAPRICE MASTER JAJB MONZA TYPHOON TEMPEST THUNDERBOLT TALISMAN CORVETTE STING RAY AD UNIVERSAL CAMARO DA MASTER MANGUSTA PANTERA DEAUVILLE LONGCHAMP BLAZER EC STANDARD MONTE CARLO EA MASTERFC STANDARDFA MASTER IMPALA MASTER GAGBHAHB CAPRICE MASTER JAJB MONZA TYPHOON TEMPEST THUNDERBOLT TALISMAN CORVETTE STING RAY AD UNIVERSAL CAMARO DA MASTER MANGUSTA PANTERA DEAUVILLE LONGCHAMP BLAZER EC STANDARD MONTE CARLO EA MASTERFC STANDARDFA MASTER IMPALA MASTER GAGBHAHB CAPRICE MASTER JAJB MONZA TYPHOON TEMPEST THUNDERBOLT TALISMAN CORVETTE STING RAY AD UNIVERSAL CAMARO DA MASTER MANGUSTA PANTERA DEAUVILLE LONGCHAMP BLAZER EC STANDARD MONTE CARLO EA MASTERFC STANDARDFA MASTER IMPALA MASTER GAGBHAHB CAPRICE MASTER JAJB MONZA TYPHOON TEMPEST THUNDERBOLT TALISMAN CORVETTE STING RAY AD UNIVERSAL CAMARO DA MASTER MANGUSTA PANTERA DEAUVILLE LONGCHAMP BLAZER EC STANDARD MONTE CARLO EA MASTERFC STANDARDFA MASTER IMPALA MASTER GAGBHAHB CAPRICE MASTER JAJB MONZA TYPHOON TEMPEST THUNDERBOLT TALISMAN CORVETTE STING RAY AD UNIVERSAL CAMARO DA MASTER MANGUSTA PANTERA DEAUVILLE LONGCHAMP BLAZER EC STANDARD MONTE CARLO EA MASTERFC STANDARDFA MASTER IMPALA MASTER GAGBHAHB CAPRICE MASTER JAJB MONZA TYPHOON TEMPEST THUNDERBOLT TALISMAN CORVETTE STING RAY AD UNIVERSAL CAMARO DA MASTER MANGUSTA PANTERA DEAUVILLE LONGCHAMP BLAZER EC STANDARD MONTE CARLO EA MASTERFC STANDARDFA MASTER IMPALA MASTER GAGBHAHB CAPRICE MASTER JAJB MONZA TYPHOON TEMPEST THUNDERBOLT TALISMAN CORVETTE STING RAY AD UNIVERSAL CAMARO DA MASTER MANGUSTA PANTERA DEAUVILLE LONGCHAMP BLAZER EC STANDARD MONTE CARLO EA MASTERFC STANDARDFA MASTER IMPALA MASTER GAGBHAHB CAPRICE MASTER JAJB MONZA TYPHOON TEMPEST THUNDERBOLT TALISMAN CORVETTE STING RAY AD UNIVERSAL CAMARO DA MASTER MANGUSTA PANTERA DEAUVILLE LONGCHAMP BLAZER EC STANDARD MONTE CARLO EA MASTERFC STANDARDFA MASTER IMPALA MASTER GAGBHAHB CAPRICE MASTER JAJB MONZA TYPHOON TEMPEST THUNDERBOLT TALISMAN CORVETTE STING RAY AD UNIVERSAL CAMARO DA MASTER MANGUSTA PANTERA DEAUVILLE LONGCHAMP BLAZER EC STANDARD MONTE CARLO EA MASTERFC STANDARDFA MASTER IMPALA MASTER GAGBHAHB CAPRICE MASTER JAJB MONZA TYPHOON TEMPEST THUNDERBOLT TALISMAN CORVETTE STING RAY AD UNIVERSAL CAMARO DA MASTER MANGUSTA PANTERA DEAUVILLE LONGCHAMP BLAZER EC STANDARD MONTE CARLO EA MASTERFC STANDARDFA MASTER IMPALA MASTER GAGBHAHB CAPRICE MASTER JAJB MONZA TYPHOON TEMPEST THUNDERBOLT TALISMAN CORVETTE STING RAY AD UNIVERSAL CAMARO DA MASTER MANGUSTA PANTERA DEAUVILLE LONGCHAMP BLAZER EC STANDARD MONTE CARLO EA MASTERFC STANDARDFA MASTER IMPALA MASTER GAGBHAHB CAPRICE MASTER JAJB MONZA TYPHOON TEMPEST THUNDERBOLT TALISMAN CORVETTE STING RAY AD UNIVERSAL CAMARO DA MASTER MANGUSTA PANTERA DEAUVILLE LONGCHAMP BLAZER EC STANDARD MONTE CARLO EA MASTERFC STANDARDFA MASTER IMPALA MASTER GAGBHAHB CAPRICE MASTER JAJB MONZA TYPHOON TEMPEST THUNDERBOLT TALISMAN CORVETTE STING RAY AD UNIVERSAL CAMARO DA MASTER MANGUSTA PANTERA DEAUVILLE LONGCHAMP BLAZER EC STANDARD MONTE CARLO EA MASTERFC STANDARDFA MASTER IMPALA MASTER GAGBHAHB CAPRICE MASTER JAJB MONZA TYPHOON TEMPEST THUNDERBOLT TALISMAN CORVETTE STING RAY AD UNIVERSAL CAMARO DA MASTER MANGUSTA PANTERA DEAUVILLE LONGCHAMP BLAZER EC STANDARD MONTE CARLO EA MASTERFC STANDARDFA MASTER IMPALA MASTER GAGBHAHB CAPRICE MASTER JAJB MONZA TYPHOON TEMPEST THUNDERBOLT TALISMAN CORVETTE STING RAY AD UNIVERSAL CAMARO DA MASTER MANGUSTA PANTERA DEAUVILLE LONGCHAMP BLAZER EC STANDARD MONTE CARLO EA MASTERFC STANDARDFA MASTER IMPALA MASTER GAGBHAHB CAPRICE MASTER JAJB MONZA TYPHOON TEMPEST THUNDERBOLT TALISMAN CORVETTE STING RAY AD UNIVERSAL CAMARO DA MASTER MANGUSTA PANTERA DEAUVILLE LONGCHAMP BLAZER EC STANDARD MONTE CARLO EA MASTERFC STANDARDFA MASTER IMPALA MASTER GAGBHAHB CAPRICE MASTER JAJB MONZA TYPHOON TEMPEST THUNDERBOLT TALISMAN CORVETTE STING RAY AD UNIVERSAL CAMARO DA MASTER MANGUSTA PANTERA DEAUVILLE LONGCHAMP BLAZER EC STANDARD MONTE CARLO EA MASTERFC STANDARDFA MASTER IMPALA MASTER GAGBHAHB CAPRICE MASTER JAJB MONZA TYPHOON TEMPEST THUNDERBOLT TALISMAN CORVETTE STING RAY AD UNIVERSAL CAMARO DA MASTER MANGUSTA PANTERA DEAUVILLE LONGCHAMP BLAZER EC STANDARD MONTE CARLO EA MASTERFC STANDARDFA MASTER IMPALA MASTER GAGBHAHB CAPRICE MASTER JAJB MONZA TYPHOON TEMPEST THUNDERBOLT TALISMAN CORVETTE STING RAY AD UNIVERSAL CAMARO DA MASTER MANGUSTA PANTERA DEAUVILLE LONGCHAMP BLAZER EC STANDARD MONTE CARLO EA MASTERFC STANDARDFA MASTER IMPALA MASTER GAGBHAHB CAPRICE MASTER JAJB MONZA TYPHOON TEMPEST THUNDERBOLT TALISMAN CORVETTE STING RAY AD UNIVERSAL CAMARO DA MASTER MANGUSTA PANTERA DEAUVILLE LONGCHAMP BLAZER EC STANDARD MONTE CARLO EA MASTERFC STANDARDFA MASTER IMPALA MASTER GAGBHAHB CAPRICE MASTER JAJB MONZA TYPHOON TEMPEST THUNDERBOLT TALISMAN CORVETTE STING RAY AD UNIVERSAL CAMARO DA MASTER MANGUSTA PANTERA DEAUVILLE LONGCHAMP BLAZER EC STANDARD MONTE CARLO EA MASTERFC STANDARDFA MASTER IMPALA MASTER GAGBHAHB CAPRICE MASTER JAJB MONZA TYPHOON TEMPEST THUNDERBOLT TALISMAN CORVETTE STING RAY AD UNIVERSAL CAMARO DA MASTER MANGUSTA PANTERA DEAUVILLE LONGCHAMP BLAZER EC STANDARD MONTE CARLO EA MASTERFC STANDARDFA MASTER IMPALA MASTER GAGB HAHB CAPRICE MASTER JAJB MONZA TYPHOON TEMPEST THUNDERBOLT TALISMAN CORVETTE STING RAY AD UNIVERSAL CAMARO DA MASTER MANGUSTA PANTERA DEAUVILLE LONGCHAMP BLAZER EC STANDARD MONTE CARLO EA MASTERFC STANDARDFA MASTER IMPALA MASTER GAGBHAHB CAPRICE MASTER JAJB MONZA TYPHOON TEMPEST THUNDERBOLT TALISMAN CORVETTE STING RAY AD UNIVERSAL CAMARO DA MASTER MANGUSTA PANTERA DEAUVILLE LONGCHAMP BLAZER EC STANDARD MONTE CARLO EA MASTERFC STANDARDFA MASTER IMPALA MASTER GAGBHAHB CAPRICE MASTER JAJB MONZA TYPHOON TEMPEST THUNDERBOLT TALISMAN}

format_products = %w{AirandFuelDelivery BodyParts Tyers BrakeParts CoolingSystem DrivelineandAxles Electrical Charging Starting Electronics Telematics Emission Control EngineParts ExhaustSystem Fluid Liquid Accessories HardwareSupplies ServiceSupplies HeatingVentilating AirConditioning IgnitionParts LightingBody Electrical SteeringParts SuspensionParts TireAndWheel ToolsAndEquipment TransferCase TransmissionAndTransaxle-Automatic TransmissionAndTransaxle-Manual WiperAndWasher }

format_items = %w{accelerator
airbag airConditioner airConditioning airFilter airVent alarm all-wheel-rive alternator antenna anti-lock-brakes armrest auto automatic-transmission automobile axle baby-car-seat baby-seat back-up-lights battery bench seat bonnet brake lightbrake-pedal brakes
bucket-seat bumper camshaft car carburetor catalytic-converter chassis child-car-seat chrome-trim clutch computer console cooling-system crankshaft cruise-control cylinder dashboard defroster disel-engine dip-stick differential door door-handle drive-belt drive-shaft driver's-seat
emergency-brake
emergency-lights
emissions engine engine-block exhaust-pipe exhaust-system fan-belt fender filter floor-mat fog-light four-wheel-drive frame fuel fuel-cap fuel-gauge fuse gas gasket gas-pedal gas-gauge gasoline gas-tank gauge gearbox gear-shift gear-stick glove-compartment GPS grille hand brake headlamp headlight headrest heater high-beam-headlights hood horn hubcap hybrid ignition instrument-panel interior-light internal-combustion-engine jack key license-plate lights lock low-beam headlights lug-bol tlug-nut manifold manual-transmission mat mirror moon-roof motor mud-flap muffler navigation-system odometer oil oil-filter oil-tank Pparking-brake parking-lights passenger-seat pedal piston power-brakes power-steering power-window-switch radiator radio rag-top rear-view mirror rear-window-defroster reverse-light rims roof roof-rack rotary-engine seat seat-belt shift shock-absorber sideAirbags sideMirror spareTire sparkPlug speaker speedometer spoiler starter steeringColumn steeringWheel sunroof sunVisor suspension tachometer tailgate temperatureGauge thermometer tire trailerHitch transmission trim tripComputer trunk turboCharger turnSignal undercarriage unleadedGas valve vents visor warningLight wheel wheel-well window windshield wind}
#movie = Movie.create( name: "umesh"director: "saruk", description: "haha haha hahaha", year: 2014 , length: 80, format: "hd")

#Movie.destroy_all

15.times do

  brand = Brand.create(
      :name => formats_brands[rand(1..formats_brands.length)],

  )

end


150.times  do
  brandlength = Brand.all.length
  brand =Brand.find_by(id: rand(1..brandlength))

  car = brand.cars.new(
      :name => formats_cars[rand(1..formats_cars.length)]
  )

  car.save
end

1500.times do

  carlength = Car.all.length
  car =Car.find_by(id: rand(1..carlength))

  product = car.products.new(
      :name => format_products[rand(1..format_products.length)]
  )

  product.save
end



3000.times do

  productlength = Product.all.length
  product =Product.find_by(id: rand(1..productlength))

  type = product.types.new(
      :name =>format_products[rand(1..format_products.length)]

  )
  type.save

end

6000.times do


  typelength = Type.all.length
  type = Type.find_by(id: rand(1..typelength))

  item = type.items.new(
      :name => format_items[ rand(1..format_items.length)],
      :image_url =>"image#{rand(1..26)}.jpg",
      :price => Commerce.price,
      :manufacturer => "#{Company.name}",
      :description => Lorem.paragraphs.join(" \n ").html_safe

  )
  item.save

end
